### ISSUE TITLE
Add server for flask to docker_compose.py

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator#16]

**Comment by lzy7071** [comment]
make docker image in which flask is running, map docker port 5000 to host port 5000

**Comment by lzy7071** [comment]
run "docker-compose up -d" for initial setup. It takes approximately 20-30min to finish because it needs to download the database archive and restore the archive to mongodb. Once the mongo-setup container disappears from the running containers in "docker ps," it means the setup is complete.
