### ISSUE TITLE
Can the equality requirement constraints be changed to >=?

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator#32]
The `==` constraint for `urllib3` in `requirements.txt` was creating problems for the installation of `datanator` in CircleCI. I converted it to a `>=` constraint, which is more flexible. Everything seems to be fine. Is there a reason why you need a specific version?

The same question applies to `datanator_query_python` (`pytz`).

**Comment by lzy7071** [comment]
I used `==` for datanator_query_python because if I bump up version number of `datanator_query_python` but don't change the number in `requirements.txt`, there will be test errors on CircleCI because the build would be using the old version of `d_q_p`.

**Comment by lzy7071** [comment]
urllib3 needs to have a version number less than 1.25 because it is a requirement from quilt3 PyPI package.

**Comment by jonrkarr** [comment]
This can be changed to 
```
urllib3 >= 1.24.2, <1.25
```

Actually, this is probably sufficient
```
urllib3 <1.25
```
