### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator#33]
I got the build running again by converting the `==` requirement constraint for `urllib3` to a `>=` constraint. There are now 11 test failures. See https://circleci.com/gh/KarrLab/datanator/2239.

**Comment by lzy7071** [comment]
- Skipped some tests that need to be done from academic IP addresses (downloading of supplementary files).
- Added `python3 setup.py install_egg_info --install-dir=/usr/local/lib/python3.7/site-packages` in circle config to avoid contextualconflict error from pip.
