### ISSUE TITLE
Add data license to quilt package

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator#36]
Add a plain text description of the CC BY-NC-ND license to the quilt data package at the path `LICENSE` within the package.

The file can be copied from here: https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.txt

**Comment by lzy7071** [comment]
I added an additional licence description [file](https://github.com/KarrLab/datanator/blob/master/LICENCE.quilt3.md) and stated explicitly that Quilt3 package was released under CC BY-NC-ND license.

**Comment by jonrkarr** [comment]
I think the name `DATA_LICENSE` makes more sense for developers who aren't yet familiar with Quilt.

**Comment by lzy7071** [comment]
[Done](https://github.com/KarrLab/datanator/commit/42ba5ff658e03ce8f0da947f33662f20c9cedda4)
