### ISSUE TITLE
Incorporate RNA modification data

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator#40]
I will add more details shortly

**Comment by jonrkarr** [comment]
## User interface
From the perspective of the UI, we can add another data table to each gene page with reconstructed mature RNA sequences (i.e., with post-transcriptionally modified nucleotides such as methylated guanine).

KEGG ortholog groups do cover rRNA and tRNA. Examples: 
- rRNA: https://www.genome.jp/dbget-bin/www_bget?ko:K01985
- tRNA: https://www.genome.jp/dbget-bin/www_bget?ko:K14237

However, I think we may need to assign rRNA and tRNA to ortholog groups because the annotation seems to be sparse. This is fairly easy. rRNA are group by canonical types (5S, 16S, 23S) and tRNA are grouped by anticodon/aminoacid.

## Data
I'm going attach a table with these columns
- string: Organism
- string: Gene ID
- string: Name
- string: KO group
- string: Unmodified sequence
- string: Modified sequence encoded with BpForms
- string: source -- this will always be MODOMICS

**Comment by lzy7071** [comment]
Data stored in `rna_modifications` collection.

I have moved the `User interface` part of the issue to `datanator_rest_api` [issue #61](https://github.com/KarrLab/datanator_rest_api/issues/61#issue-608681022). As such, this issue is closed.
